### ISSUE TITLE
Table name too long

### ISSUE THREAD

**Issue by spencerdlin** [pinterest/pinball#16]
Setup:
MySQL:  mysql  Ver 14.14 Distrib 5.6.17, for osx10.9 (x86_64) using  EditLine wrapper

Pinball given root credentials to MySQL db.

Error:
When I run:
python -m pinball.run_pinball -c path/to/pinball/yaml/configuration/file -m master

I get the following error:
Creating tables ...
Creating table active_tokens_NFYC2MJZGIWTCNRYFUYTEOBNGI2DOLTFMMZC42LOORSXE3TBNQ______
django.db.utils.DatabaseError: (1059, "Identifier name 'active_tokens_NFYC2MJZGIWTCNRYFUYTEOBNGI2DOLTFMMZC42LOORSXE3TBNQ______' is too long")

**Comment by spencerdlin** [comment]
Sanitization of the hostname can lead to very long names that are too long to be mysql table names.
https://github.com/pinterest/pinball/blob/master/pinball/config/utils.py#L90

**Comment by MaoYe** [comment]
@spencerdlin  thanks for reporting this. We have a configuration parameter in the yaml file can help with this. check the field for "master_name" and put a name like "your_name". The db table will be constructed as "active_tokens_your_name".  Thanks!
