### ISSUE TITLE
Long hostnames leads to too long table names

### ISSUE THREAD

**Issue by mrunesson** [pinterest/pinball#19]
Most tables has a limit on table names to about 64 characters. Some tables are base64 encoded hostname postfixed and can end up in longer table names than 64 characters.

**Comment by MaoYe** [comment]
@mrunesson thanks for reporting this. We have a configuration parameter in the yaml file can help with this. check the field for "master_name" and put a name like "your_name". The db table will be constructed as "active_tokens_your_name". Thanks!
