### ISSUE TITLE
luigi

### ISSUE THREAD

**Issue by imazor** [pinterest/pinball#24]
Hi,

I am not sure if its the right place to ask such questions, but I have not found other suitable place.

My main question is what he major difference between your project and Luigi?
Why one should use pinball and not luigi ?
 
* just to clarify,  I am not represent luigi in any way, I am truly would like to know what the differences between the 2 projects, so with the time I can choose the right tool for my needs.

Thanks,

**Comment by MaoYe** [comment]
@imazor When Pinball starts, Luigi is not public accessible yet.
When we build pinball, we aim to build a scalable and flexible workflow manager to satisfy the the following requirements (I just name a few here).
1. easy system upgrade - when we fix bug or adding new features, there should be no interruption for current running workflow and jobs. 
2. easy add/test workflow - end user can easily add new jobs and workflows into pinball system, without affecting other running jobs and workflows. 
3. extensibility - a workflow manager should be easy to extended. As the company and business grows, there will be a lot new requirements and features needed. And also we love your contributions as well. 
4. flexible workflow scheduling policy, easy failure handling. 
5. We provide rich UI for you to easily manage your workflows - auto retry failed job, - you can retry failed job, can skip some job, can select a subset of jobs of a workflow to run (all from UI) - you can easily access all the running history of your job, and also get the stderr, stdout logs of your jobs - you can also explore the topology of your workflow, and also support easy search. 
6. Pinball is very generic can support different kind platform, you can use different hadoop clusters,e.g., quoble cluster, emr cluster. You can write different kind of jobs, e.g., hadoop streaming, cascading, hive, pig, spark, python ...

There are a lot interesting things built in Pinball, and you probably want to have a try!

You can just follow the readme to get Pinball easily setup. Feel free to let us know if there is any questions. Thanks for the interests to Pinball.

**Comment by imazor** [comment]
Hi,

Thanks for the answer, indeed sounds interesting.
How do you handle job dependencies?
In luigi an output must be exist (like file) on which existences can be
verified, is this also the case for pinball?

Can you maybe give some kind of estimation, for how much effort it will
take to migrate from luigi to pinball?

Thanks,
Am 21.03.2015 08:32 schrieb "Mao Ye" <notifications@github.com>:

**Comment by pgarbacki** [comment]
Pinball dependencies are based on the run-after principle. A downstream job
will kick off after all its upstream dependents finish successfully. We
don't enforce output existence requirements.

The migration effort depends on the structure of your jobs. Take a look at
the tutorial <https://github.com/pinterest/pinball/tree/master/tutorial> to
get an idea how Pinball workflows are defined.
