### ISSUE TITLE
Lack of direction on where to begin helping with documentation

### ISSUE THREAD

**Issue by ybur-yug** [pinterest/pinball#28]
Hey guys,

First of all, great work! And way to open source it!

I have built a framework in the past quite similar for such workflow management, and it really seems as if you guys have hit the nail firmly on the head.

I would love to contribute. Obviously, with a codebase this large and being fresh out of the doors, core code contributions are a fleeting dream. However, I would love to help you further documentation.

I have checked 

https://github.com/pinterest/pinball/blob/master/CONTRIBUTING.rst

and it says more docstrings and further documentation are welcome, but I would love an example of where to start. I would gladly add to whatever you think is more important.

Is there a slack room, IRC channel, or gitter.im room where I could talk to other contributors?
Or is there a kanban board of sorts to grab/make cards for documentation specific tasks?

If not, I'd gladly assist in whatever way I could to set it up. Look forward to hearing back from you guys.

Cheers,
Bobby

PS sorry for opening it as an issue, I just figured it was the easiest means of communication, feel free to close it and email me at bobbygrayson[at]gmail[dot]com

**Comment by rhgraysonii** [comment]
@jparise youre the first random name to come up I can tag and its been a bit. Thoughts?

**Comment by MaoYe** [comment]
@rhgraysonii Thanks for your interests in Pinball and the willing to contribute to it. We've have mostly of documentation done. We do love to rich our document about the user tutorial which helps user quickly setup pinball and write their jobs e.g., hive, hadoop, spark..  For those documentation tasks requires the understanding of Pinball. I would encourage you to go through pinball readme page to get familiar with pinball, and set it up. Then, play with it and get a basic sense and go through current tutorial cases we've provided. After all those done, I'd assume you will have more interests in reading our Pinball code a bit and thinking about what is missing in the tutorial documentations. Thanks a lot!

**Comment by rhgraysonii** [comment]
@MaoYe I have set it up locally already and began exploring code :) I will continue to, and definitely go into the depths of the current tutorial docs. I haven't yet gone through all cases but have done a couple. I really think you guys are doing some awesome stuff and will definitely keep following.

**Comment by MaoYe** [comment]
Just close this as this has been discussed already.
