### ISSUE TITLE
Set up to correctly read logs?

### ISSUE THREAD

**Issue by Tjorriemorrie** [pinterest/pinball#35]
We're using python scripts mostly, and has set up our scripts to correctly use the stderr and stdout channels:
```
        'stdout': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': 'ext://sys.stdout',
        },
        'stderr': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': 'ext://sys.stderr',
        },
```

We have one master: running the master, ui, and scheduler service. We have two worker machines: each running the worker service. When we try to see the logs of a job: we keep getting the error:
```
Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/pinball-0.1.1-py2.7.egg/pinball/ui/views.py", line 185, in file_content execution, log_type) 
File "/usr/local/lib/python2.7/dist-packages/pinball-0.1.1-py2.7.egg/pinball/ui/data_builder.py", line 843, in get_file_content f.close() 
File "/usr/local/lib/python2.7/dist-packages/pinball-0.1.1-py2.7.egg/pinball/workflow/log_saver.py", line 101, in close self._file_descriptor.close() 
AttributeError: 'NoneType' object has no attribute 'close'
```

It seems master is trying to read the logs on it's own disk, instead of reading it from the worker. What is wrong with our set up to enable us to read the logs. It works fine when we tested it and the worker service was running on the master self.

**Comment by MaoYe** [comment]
@Tjorriemorrie If the worker and master/UI are in different machines. We should enable some settings in the yaml configuration files such that, 1) worker store its logs in some remote storage (our default implementation is s3); 2) master/ui read the log from the remote storage (s3 is our default implementation).

Here is some configuration settings:
https://github.com/pinterest/pinball/blob/master/pinball/config/default.yaml#L41
https://github.com/pinterest/pinball/blob/master/pinball/config/default.yaml#L45

Please let us know if you still see any issues, thanks a lot!
