### ISSUE TITLE
How many days to save the log of workflow at Pinterest?

### ISSUE THREAD

**Issue by sungjuly** [pinterest/pinball#41]
Hi guys,

I have experienced a performance issue since few days. In my case, the pinball logs are over 50,000 records. Of course, I've fixed this issue after moving some records to another table.

As you know, basically the token persistent layer of pinball has a limitation of performance due to `like` operation even if cache is enabled.
https://github.com/pinterest/pinball/blob/master/pinball/persistence/store.py#L267

I'm wondering how many days to save the log of workflow at Pinterest? Is 4 weeks, right?
https://github.com/pinterest/pinball/blob/master/pinball/tools/workflow_util.py#L1260

**Comment by pgarbacki** [comment]
FWIW., at Pinterest we keep workflows around for a couple of months.

**Comment by sungjuly** [comment]
@pgarbacki Thanks!
