### ISSUE TITLE
add caller/source info in the parameter pass down to config_parser

### ISSUE THREAD

**Issue by csliu** [pinterest/pinball#43]
In the project I am working on, I need to differentiate who is calling the parser, for example, it's UI, scheduler or some other tool/lib.

the parameter passed down to parser is a map, that's great, so we can add another key 'caller' to it and this won't affect previous code.

how do you think about it? @pgarbacki @MaoYe

**Comment by pgarbacki** [comment]
Can you tell a bit more why you need to pass along the caller identity?

**Comment by csliu** [comment]
Basically, my own parser's: config_parser.get_workflow_token() will have some side effect. so we want to control the side effect. If we can tell where the call comes from, such as the call is from UI (schedule page), we might go a no-side-effect code path in get_workflow_token(). If the call is from scheduler, then we will go the code path that have some side-effect.

**Comment by csliu** [comment]
PR: https://github.com/pinterest/pinball/pull/46/files
