### ISSUE TITLE
Getting started with Pinball

### ISSUE THREAD

**Issue by maxwintko** [pinterest/pinball#51]
Hi 

I am very new to Pinball and want to use it in my project. I have looked at getting-started guide to have pinball up and running , and imported example workflow as mentioned in the guide. But I dont know where to go after that, i cant find enough tutorial on the net also.

For my project, i might need to create my own workflow such as fetching some webpage, send them to parsers and indexers, archive the data, store some images, scan through log files, restart app server etc. Can somebody please guide me where i should start learning/using pinball. 

Thanks in advance 
Max

**Comment by csliu** [comment]
as the first step, you can try to add new jobs/workflows under this folder:
https://github.com/pinterest/pinball/tree/master/tutorial/example_repo

And follow the tutorial on how to import/run them.

Going further, you can read the comments of the following config on how to customize Pinball:
https://github.com/pinterest/pinball/blob/master/tutorial/example_repo/tutorial.yaml
