### ISSUE TITLE
Executor failed on job ownership

### ISSUE THREAD

**Issue by Tjorriemorrie** [pinterest/pinball#59]
Receiving the following error via pinlog:

> executor failed to renew job ownership on time

I'm having trouble resolving this and was wondering if you know perhaps anything about it?

The job is a CommandLineJob that does an ssh to another box. The job runs about 30 minutes, then the script finished, but pinball then fails with above.

I don't think it's the ServerAliveInterval, I've tried that.

**Comment by csliu** [comment]
@Tjorriemorrie it will be better if you can paste the stack trace here.

**Comment by csliu** [comment]
also, the err msg you pasted will only show up if the *previous* execution of a job failed to renew the ownership. Basically, the message is printed when preparing the current execution of a job.

closing it for now, let me know if you still need any help here.
