### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [pinterest/pinball#74]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like _pinball_, deleted their software history.

https://github.com/pinterest/pinball/commit/9dc683dfa93eafbfdf64d77ae4ab3470ebbb398f

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask pinball developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by gustavopinto** [comment]
hi @pgarbacki, do you have any comments?

**Comment by jparise** [comment]
@gustavopinto Pinball was originally extracted from an larger internal source repository. At the time, moving the code into a new repository in preparation for it being released as an independent package was the easiest path forward.

**Comment by gustavopinto** [comment]
Hi @jparise,

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
