### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by rizplate** [pinterest/pinball#88]
Really bad documentation. I can't figure out anything.

Is this thing distributed? can I run workers on different machine?
What is the datastore that holds job and schedule information , is it a database or filesystem?

**Comment by anshulpundir** [comment]
Pinball uses MySQL to store job/schedule info. This is actually mentioned in the README:
"Pinball uses mysql as persistent storage. Please also make sure mysql is available, and properly configured."

There's more info there on setting up MySQL.

You can definitely run workers on different. Agreed that this is not clear from the documentation.

**Comment by rizplate** [comment]
ok thanks.
