### ISSUE TITLE
pypi seems to be broken with pydot version

### ISSUE THREAD

**Issue by smboy** [pinterest/pinball#9]
<code>Collecting pydot==1.0.28 (from pinball)
  Could not find a version that satisfies the requirement pydot==1.0.28 (from pinball) (from versions: 1.0.2)
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external to allow).
  No distributions matching the version for pydot==1.0.28 (from pinball)
<code>

I'm assuming it should be pydot==1.0.2 instead of 1.0.28

<code>
sudo pip install pydot
The directory '/Users/smallem/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
You are using pip version 6.0.7, however version 6.0.8 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/Users/smallem/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Collecting pydot
  Downloading pydot-1.0.2.tar.gz
    Couldn't import dot_parser, loading of dot files will not be possible.
Requirement already satisfied (use --upgrade to upgrade): pyparsing in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pydot)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Library/Python/2.7/site-packages (from pydot)
Installing collected packages: pydot
  Running setup.py install for pydot
    Couldn't import dot_parser, loading of dot files will not be possible.
Successfully installed pydot-1.0.2
<code>

**Comment by pgarbacki** [comment]
Thanks for the report. We will look into it. In the meantime, you may want to force the installation of the most recent version of pydot with this command:
pip install --allow-unverified pydot pydot==1.0.28

**Comment by MaoYe** [comment]
Hi, @smboy:

I tested pydot-1.0.2 with Pinball, and it will breaks the svg graph in pinball UI. 

pydot-1.0.28 is accessible at https://pypi.python.org/pypi/pydot/1.0.28 

Do you have some special setting in your pip.conf and make you failed to find pydot==1.0.28?

**Comment by smboy** [comment]
Thanks for checking. I've downloaded pydot-1.0.28 manually. I dont have any special setting for pip.conf.
